new k8s guide
checkly/docs.checklyhq.com pull request #1112
Opened 2024-10-30 11:49 UTC by serverless-mom

## Affected Components
* [ ] Content & Marketing
* [ ] Pricing
* [ ] Test
* [x] Docs
* [ ] Learn
* [ ] Other

Okay, so, this isn't a guide for Checkly, but... it didn't fit well in any /Learn category. Maybe I should have created it as a blog post?!? 😭 

Anyhoo, if we get a few more K8s articles for /Learn we can migrate this over there.

2024-11-05 11:42 UTC, tnolet requested changes
the content is hard to consume due to lack of paragraphs. Could also be more concise

2024-11-05 11:42 UTC, tnolet commented on site/content/guides/kuberhealthy-vs-prometheus-blackbox-exporter.md
> +We all implement tools to monitor our nodes and keep our entire cluster up and running. But how often do updates, failures, or errors mean that users suffer outages, even though our status boards loo
this section is way too long and has no paragraph breaks, making it hard to read.

2024-11-05 11:42 UTC, tnolet commented on site/content/guides/kuberhealthy-vs-prometheus-blackbox-exporter.md
> +Prometheus Blackbox exporter is a completely free and open source tool, released under the Apache 2.0 license. That means no hidden fees, no surprise changes to SaaS terms, or the other vagaries that
Add paragraphs. This is a block of text.

2024-11-05 11:42 UTC, tnolet commented on site/content/guides/kuberhealthy-vs-prometheus-blackbox-exporter.md
> +However, notice what’s not included in this basic set of examples: nothing about checking a random URL’s API response and parsing the response. The focus here is on the health of components internal
add paragraphs.

2024-11-06 01:44 UTC, Dgiordano33 reviewed
This looks like general information for other tooling around k8s. To me, it feels like a good blog. 

A guide should use Checkly. A learn article should teach foundational skills. This feels like something for the blog where we give an opinion on something our readers are interested in.

2024-11-07 15:31 UTC, Dgiordano33 commented
@serverless-mom Could you just bring this to the blog and then close this PR down?

2024-11-08 20:23 UTC, closed without merging

2024-12-02 18:19 UTC, serverless-mom commented
Moved to blog here: https://www.checklyhq.com/blog/prometheus-blackbox-exporter-vs-kuberhealthy/