WIP: alerting overview page
checkly/docs.checklyhq.com pull request #931
Opened 2023-10-24 20:13 UTC by ragog

## Affected Components
* [ ] Content & Marketing
* [ ] Pricing
* [ ] Test
* [x] Docs
* [ ] Learn
* [ ] Other

## Pre-Requisites
* [ ] Code is linted (`npm run lint`)

2023-10-24 22:33 UTC, ragog commented
@drakirnosslin I am finally catching up with something we agreed upon some time ago: we should have an overview section for Alerting in the docs which explains what is what. This came out of many, many people being confused about where Alert Settings end and Alert Channels begin (especially in the context of groups). For that I will ping you again in Slack with some additional suggestions about small product changes to make that more apparent.

@stefanjudis Also tagging you as I would like to hear your thoughts here. Also, am I breaking 100 redirects here? Always paranoid about that one :)

2023-10-25 07:54 UTC, drakirnosslin approved these changes

2023-10-25 08:31 UTC, stefanjudis requested changes
I think this makes a lot of sense. I added a small nit, though. :) 

When this goes live, we have to time things a little to [tweak and adjust all the existing redirects](https://github.com/checkly/checkly-marketing-website/blob/main/next.config.js#L174-L176). @pilimartinez can help out here. :) 

We also have to check the marketing site to find all the occasions where we link to the alerting section of the docs. Ideally, we link to proper `200`s instead of `308` from/in our own properties. :)

2023-10-25 08:31 UTC, stefanjudis commented on site/content/docs/alerting-and-retries/_index.md
> +Checkly will alert you when your checks [change state](/docs/retries-and-alerting/alert-states), e.g. when a passing check starts failing. To make the most out of Checkly alerts, you will want to con
I think this URL 404s after your changes. :)

2023-11-02 14:40 UTC, merged