feat: add playwright config documentation
checkly/docs.checklyhq.com pull request #973
Opened 2024-01-17 09:45 UTC by ferrandiaz

## Affected Components
* [ ] Content & Marketing
* [ ] Pricing
* [ ] Test
* [x] Docs
* [ ] Learn
* [ ] Other

## Pre-Requisites
* [x] Code is linted (`npm run lint`)

## Notes for the Reviewer
Documentation for supported options of playwright config

2024-01-19 11:05 UTC, tnolet approved these changes
@ferrandiaz I made some tweaks. Here are some tips for the future. Nice work on the matrix

1.  Capitalize brand names. Checkly and Playwright.
2. Reduce duplication.

2024-01-19 11:47 UTC, ferrandiaz commented on site/content/docs/browser-checks/playwright-test.md
> +There three things you should be aware of:
```suggestion
There are three things you should be aware of:
```

2024-01-19 11:47 UTC, ferrandiaz commented on site/content/docs/browser-checks/playwright-test.md
> +This command will all currently supported Playwright config option to your `checkly.config.ts` file.
```suggestion
This command will add currently supported Playwright config option to your `checkly.config.ts` file.
```

2024-01-19 13:51 UTC, tnolet approved these changes
LGTM

2024-01-25 14:06 UTC, tnolet requested changes
pay attention to the document structure and end sentences with a .

2024-01-25 14:06 UTC, tnolet commented on site/content/docs/cli/command-line-reference.md
> +### `npx checkly sync-playwright`
```suggestion
## `npx checkly sync-playwright`
```

2024-01-25 14:06 UTC, tnolet commented on site/content/docs/cli/command-line-reference.md
> +Copy Playwright config into the Checkly config file
```suggestion
Copy Playwright config into the Checkly config file.
```

2024-01-26 08:37 UTC, merged