added new websockets page
checkly/docs.checklyhq.com pull request #975
Opened 2024-01-17 14:37 UTC by checklyalex

## Affected Components
* [ ] Content & Marketing
* [ ] Pricing
* [ ] Test
* [x] Docs
* [ ] Learn
* [ ] Other

## Pre-Requisites
* [ ] Code is linted (`npm run lint`)

## Notes for the Reviewer

## New Dependency Submission

## Screenshots

2024-01-17 14:51 UTC, ragog requested changes
@checklyalex left a couple of comments on things we should address.

2024-01-17 14:51 UTC, ragog commented on site/content/docs/multistep-checks/websockets.md
> +## Set Up the WebSocket Connection
@checklyalex this is too drawn out, let's not have a chapter for each small bit of the check. Let's instead have two chapters, one for the generic websocket check code, with comments, an one for the example.

2024-01-17 14:51 UTC, ragog commented on site/content/docs/multistep-checks/websockets.md
> +- Message Validation: Add logic to validate incoming messages to ensure the data integrity.
@checklyalex nit: isn't the "the" extra here? "Data integrity"

2024-01-17 14:51 UTC, ragog commented on site/content/docs/multistep-checks/websockets.md
> +Monitoring WebSocket connections is crucial for real-time applications. With Checkly, you can easily set up checks to ensure your WebSocket connections are reliable and performant. Adjust the example
@checklyalex feels extra, let's drop this

2024-01-17 14:51 UTC, ragog commented on site/content/docs/multistep-checks/websockets.md
> +{{< tabs "Full WebSocket Script" >}}
@checklyalex question: wouldn't we want some assertions in the check? Or would you say they are superfluous?

2024-01-18 11:40 UTC, tnolet submitted a review, later dismissed
Nice addition, just drop the wikipedia and sales pitch 😄

2024-01-18 11:40 UTC, tnolet commented on site/content/docs/multistep-checks/websockets.md
> +WebSockets provide a way to establish a persistent, full-duplex communication channel that operates over a single, long-held request, enabling real-time data transfer between a client and a server.
No need to explain what websockets are and how they work. This is not wikipedia

2024-01-18 11:40 UTC, tnolet commented on site/content/docs/multistep-checks/websockets.md
> +Monitoring WebSocket connections is crucial for real-time applications. With Checkly, you can easily set up checks to ensure your WebSocket connections are reliable and performant. Adjust the example
No need to add the sales pitch at the end. These are reference docs.

2024-01-18 20:22 UTC, ragog approved these changes
@checklyalex LGTM. Let's keep an eye out for better examples if we come across them.

2024-01-19 11:42 UTC, merged